allowBuilds:
  msw: false
  sharp: false
  supabase: true
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - fflate@0.7.5
overrides:
  fflate: '>=0.7.5'
  satori>fflate: '>=0.7.5'
