import type { Metadata } from "next";
import { inter, lexend } from "@/commons/styles/fonts";
import "@/commons/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
import { SubscriptionGuard } from "@/components/subscription/guard";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${lexend.variable} theme-luluzinha antialiased`}
        suppressHydrationWarning
      >
        <SubscriptionGuard />
        {children}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
